# Generated by Django 5.1.5 on 2025-01-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='image',
            field=models.ImageField(default='work_images/default.png', upload_to='work_images/'),
        ),
        migrations.AlterField(
            model_name='works',
            name='reference',
            field=models.URLField(),
        ),
    ]
